In [304]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [264]:
df = pd.read_csv(r"c:\Users\Admin\Downloads\house_cleaned.csv",encoding='Latin')
print(df)

                                        property_name property_type  \
0      5 Bedroom House for sale in Sector 70A Gurgaon         house
1    5 Bedroom House for sale in Sector 21A Faridabad         house
2    10 Bedroom House for sale in Sushant Lok Phase 1         house
3      21 Bedroom House for sale in Sector 54 Gurgaon         house
4    12 Bedroom House for sale in Sushant Lok Phase 1         house
..                                                ...           ...
959     4 Bedroom House for sale in Sector 26 Gurgaon         house
960           3 Bedroom House for sale in DLF Phase 2         house
961     3 Bedroom House for sale in Sector 26 Gurgaon         house
962     3 Bedroom House for sale in Sector 26 Gurgaon         house
963                3 Bedroom House for sale in Bissar         house

                                      society  price  price_per_sqft    area  \
0                            bptp visionnaire   5.25         20115.0  2610.0
1                                 independent   5.70        105751.0   539.0
2                                 independent   2.10         38251.0   549.0
3                                 independent   5.00         43066.0  1161.0
4                                 independent   3.00         53763.0   558.0
..                                        ...    ...             ...     ...
959                          dlf city phase 1   5.50         30556.0  1800.0
960                    dlf city plots phase 2   4.25         31481.0  1350.0
961                          dlf city phase 1   4.50         33333.0  1350.0
962                          dlf city phase 1   3.25         33129.0   981.0
963  silverglades tarudhan valley golf resort   3.60         14815.0  2430.0

                    areaWithType  bedRoom  bathroom balcony  \
0    Plot area 290(242.48 sq.m.)        5         4      3+
1     Plot area 539(50.07 sq.m.)        5         4       2
2         Plot area 61(51 sq.m.)       10        10      3+
3    Plot area 129(107.86 sq.m.)       21        21      3+
4      Plot area 62(51.84 sq.m.)       12        12      3+
..                           ...      ...       ...     ...
959  Plot area 200(167.23 sq.m.)        4         4       3
960  Plot area 150(125.42 sq.m.)        3         2       3
961  Plot area 150(125.42 sq.m.)        3         3       2
962   Plot area 109(91.14 sq.m.)        3         3       3
963  Plot area 270(225.75 sq.m.)        3         3       2

                                additionalRoom  \
0                                 servant room
1           store room,pooja room,servant room
2                                 servant room
3                                 servant room
4                                       others
..                                         ...
959         pooja room,study room,servant room
960                                 study room
961                    study room,servant room
962                                 study room
963  pooja room,study room,servant room,others

                                         address  floorNum      facing  \
0      29b, Sector 70A Gurgaon, Gurgaon, Haryana       3.0  North-East
1         Sector 21A Faridabad, Gurgaon, Haryana       2.0         NaN
2          Sushant Lok Phase 1, Gurgaon, Haryana       5.0        West
3            Sector 54 Gurgaon, Gurgaon, Haryana       5.0       North
4    1228, Sushant Lok Phase 1, Gurgaon, Haryana       5.0        West
..                                           ...       ...         ...
959          Sector 26 Gurgaon, Gurgaon, Haryana       2.0  North-East
960                DLF Phase 2, Gurgaon, Haryana       2.0       North
961          Sector 26 Gurgaon, Gurgaon, Haryana       2.0        East
962          Sector 26 Gurgaon, Gurgaon, Haryana       2.0        West
963                     Bissar, Gurgaon, Haryana       2.0         NaN

        agePossession                                    nearbyLocations  \
0     0 to 1 Year Old  ['Good Earth City Center 2', 'Kunskapsskolan I...
1    5 to 10 Year Old                                                NaN
2     0 to 1 Year Old  ['Sector 42-43 metro station', 'Huda city cent...
3     1 to 5 Year Old  ['Sector 53-54 metro station', 'Sector 54 chow...
4     Within 6 months  ['Sector 42-43 metro station', 'Huda city cent...
..                ...                                                ...
959  5 to 10 Year Old  ['Dlf phase 1 metro station', 'Sikandarpur met...
960      10+ Year Old  ['Sahara Mall', 'Delhi Public School', 'Privat...
961  5 to 10 Year Old  ['Dlf phase 1 metro station', 'Sikandarpur met...
962      10+ Year Old  ['Dlf phase 1 metro station', 'Sikandarpur met...
963  5 to 10 Year Old                                                NaN

                                           description  \
0    Do you wish to buy an independent house in sec...
1    Hi, we have an independent house/villa availab...
2    Monthly rental income is rs1,40,000/- Best opt...
3    129 sq yd plot size. 5 floors built up , fully...
4    Best for investment purpose. Fully furnished b...
..                                                 ...
959  Residential house, g block, dlf phase-1, gurga...
960  Residential house, k block, dlf phase-2, gurga...
961  Residential house, e block 150 sq.Yds , dlf ph...
962  Residential house, e block, dlf phase-1, gurga...
963  This 3 bhk house for sale in bissar is an idea...

                                        furnishDetails  \
0    ['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...
1    ['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...
2    ['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...
3    ['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...
4    ['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...
..                                                 ...
959  ['10 Light', 'No AC', 'No Bed', 'No Chimney', ...
960                                                NaN
961  ['6 Fan', '20 Light', 'No AC', 'No Bed', 'No C...
962  ['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...
963  ['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...

                                              features  \
0    ['Feng Shui / Vaastu Compliant', 'Private Gard...
1    ['Private Garden / Terrace', 'Park', 'Visitor ...
2    ['Maintenance Staff', 'Water Storage', 'Visito...
3    ['Feng Shui / Vaastu Compliant', 'Private Gard...
4    ['Maintenance Staff', 'Water Storage', 'Visito...
..                                                 ...
959  ['Feng Shui / Vaastu Compliant', 'High Ceiling...
960  ['High Ceiling Height', 'Maintenance Staff', '...
961  ['Feng Shui / Vaastu Compliant', 'Private Gard...
962  ['Feng Shui / Vaastu Compliant', 'Private Gard...
963  ['Centrally Air Conditioned', 'Water purifier'...

                                                rating
0    ['Environment5 out of 5', 'Lifestyle4 out of 5...
1                                                  NaN
2    ['Environment5 out of 5', 'Lifestyle5 out of 5...
3    ['Environment4 out of 5', 'Lifestyle5 out of 5...
4    ['Environment5 out of 5', 'Lifestyle5 out of 5...
..                                                 ...
959                                                NaN
960  ['Environment5 out of 5', 'Safety5 out of 5', ...
961                                                NaN
962                                                NaN
963                                                NaN

[964 rows x 20 columns]

In [265]:
df.to_csv("House Prices in goregaon",index=False)

In [266]:
print(df.shape)

(964, 20)

In [267]:
print(df.columns)

Index(['property_name', 'property_type', 'society', 'price', 'price_per_sqft',
       'area', 'areaWithType', 'bedRoom', 'bathroom', 'balcony',
       'additionalRoom', 'address', 'floorNum', 'facing', 'agePossession',
       'nearbyLocations', 'description', 'furnishDetails', 'features',
       'rating'],
      dtype='object')

In [273]:
df.drop(columns=['address'])

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,4 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,5.50,30556.0,1800.0,Plot area 200(167.23 sq.m.),4,4,3,"pooja room,study room,servant room",2.0,North-East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, g block, dlf phase-1, gurga...","['10 Light', 'No AC', 'No Bed', 'No Chimney', ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...",NaN
960,3 Bedroom House for sale in DLF Phase 2,house,dlf city plots phase 2,4.25,31481.0,1350.0,Plot area 150(125.42 sq.m.),3,2,3,study room,2.0,North,10+ Year Old,"['Sahara Mall', 'Delhi Public School', 'Privat...","Residential house, k block, dlf phase-2, gurga...",NaN,"['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Safety5 out of 5', ..."
961,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,4.50,33333.0,1350.0,Plot area 150(125.42 sq.m.),3,3,2,"study room,servant room",2.0,East,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block 150 sq.Yds , dlf ph...","['6 Fan', '20 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
962,3 Bedroom House for sale in Sector 26 Gurgaon,house,dlf city phase 1,3.25,33129.0,981.0,Plot area 109(91.14 sq.m.),3,3,3,study room,2.0,West,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...","Residential house, e block, dlf phase-1, gurga...","['5 Fan', '16 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
963,3 Bedroom House for sale in Bissar,house,silverglades tarudhan valley golf resort,3.60,14815.0,2430.0,Plot area 270(225.75 sq.m.),3,3,2,"pooja room,study room,servant room,others",2.0,NaN,5 to 10 Year Old,NaN,This 3 bhk house for sale in bissar is an idea...,"['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [276]:
df[['property_type','price','price_per_sqft','bedRoom', 'bathroom', 'balcony',
       'additionalRoom','rating','floorNum', 'facing', 'agePossession']].head()

,property_type,price,price_per_sqft,bedRoom,bathroom,balcony,additionalRoom,rating,floorNum,facing,agePossession
0,house,5.25,20115.0,5,4,3+,servant room,"['Environment5 out of 5', 'Lifestyle4 out of 5...",3.0,North-East,0 to 1 Year Old
1,house,5.70,105751.0,5,4,2,"store room,pooja room,servant room",NaN,2.0,NaN,5 to 10 Year Old
2,house,2.10,38251.0,10,10,3+,servant room,"['Environment5 out of 5', 'Lifestyle5 out of 5...",5.0,West,0 to 1 Year Old
3,house,5.00,43066.0,21,21,3+,servant room,"['Environment4 out of 5', 'Lifestyle5 out of 5...",5.0,North,1 to 5 Year Old
4,house,3.00,53763.0,12,12,3+,others,"['Environment5 out of 5', 'Lifestyle5 out of 5...",5.0,West,Within 6 months

In [278]:
data=df[['property_type','price','price_per_sqft','bedRoom', 'bathroom', 'balcony',
       'additionalRoom','rating','floorNum', 'facing', 'agePossession']]
data.head(10)

,property_type,price,price_per_sqft,bedRoom,bathroom,balcony,additionalRoom,rating,floorNum,facing,agePossession
0,house,5.25,20115.0,5,4,3+,servant room,"['Environment5 out of 5', 'Lifestyle4 out of 5...",3.0,North-East,0 to 1 Year Old
1,house,5.70,105751.0,5,4,2,"store room,pooja room,servant room",NaN,2.0,NaN,5 to 10 Year Old
2,house,2.10,38251.0,10,10,3+,servant room,"['Environment5 out of 5', 'Lifestyle5 out of 5...",5.0,West,0 to 1 Year Old
3,house,5.00,43066.0,21,21,3+,servant room,"['Environment4 out of 5', 'Lifestyle5 out of 5...",5.0,North,1 to 5 Year Old
4,house,3.00,53763.0,12,12,3+,others,"['Environment5 out of 5', 'Lifestyle5 out of 5...",5.0,West,Within 6 months
5,house,4.50,39062.0,20,20,3+,servant room,"['Environment5 out of 5', 'Lifestyle5 out of 5...",4.0,East,1 to 5 Year Old
6,house,12.00,37037.0,5,5,3+,"servant room,pooja room,store room","['Environment3 out of 5', 'Lifestyle4 out of 5...",3.0,East,0 to 1 Year Old
7,house,20.00,48889.0,16,16,3+,servant room,"['Environment5 out of 5', 'Lifestyle5 out of 5...",4.0,NaN,0 to 1 Year Old
8,house,10.85,38150.0,6,6,1,store room,"['Environment5 out of 5', 'Lifestyle5 out of 5...",3.0,North-East,1 to 5 Year Old
9,house,1.95,10077.0,3,4,3+,servant room,"['Environment5 out of 5', 'Lifestyle5 out of 5...",4.0,West,0 to 1 Year Old

In [279]:
print(data.columns)

Index(['property_type', 'price', 'price_per_sqft', 'bedRoom', 'bathroom',
       'balcony', 'additionalRoom', 'rating', 'floorNum', 'facing',
       'agePossession'],
      dtype='object')

In [280]:
print(data.shape)

(964, 11)

In [281]:
print(pd.isnull(data).sum())

property_type       0
price              19
price_per_sqft     19
bedRoom             0
bathroom            0
balcony             0
additionalRoom      0
rating            121
floorNum           19
facing            303
agePossession       0
dtype: int64

In [282]:
print(data.iloc[13]) #gives me the whole data of property
# print(data.additionalRoom.head(20))
# print(data.additionalRoom[13])

property_type                                                 house
price                                                          15.0
price_per_sqft                                              33200.0
bedRoom                                                           5
bathroom                                                          6
balcony                                                          3+
additionalRoom        pooja room,study room,servant room,store room
rating            ['Environment5 out of 5', 'Lifestyle5 out of 5...
floorNum                                                        3.0
facing                                                        North
agePossession                                      5 to 10 Year Old
Name: 13, dtype: object

In [283]:
print(data.dtypes)

property_type      object
price             float64
price_per_sqft    float64
bedRoom             int64
bathroom            int64
balcony            object
additionalRoom     object
rating             object
floorNum          float64
facing             object
agePossession      object
dtype: object

In [286]:
#seperated the data into num_col or not_num_col 
num_col = ['price','price_per_sqft','bedRoom','bathroom','floorNum'] 
cat_col =  ['property_type', 'balcony', 'additionalRoom', 'rating', 'facing', 'agePossession']
print(cat_col)

['property_type', 'balcony', 'additionalRoom', 'rating', 'facing', 'agePossession']

In [287]:
for c in cat_col:
    data[c] = data[c].astype(str)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\156856382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[c] = data[c].astype(str)
C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\156856382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[c] = data[c].astype(str)
C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\156856382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[c] = data[c].astype(str)
C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\156856382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[c] = data[c].astype(str)
C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\156856382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[c] = data[c].astype(str)
C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\156856382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[c] = data[c].astype(str)

In [288]:
print(data[num_col].dtypes)
print(data[cat_col].dtypes)

price             float64
price_per_sqft    float64
bedRoom             int64
bathroom            int64
floorNum          float64
dtype: object
property_type     object
balcony           object
additionalRoom    object
rating            object
facing            object
agePossession     object
dtype: object

In [289]:
# data.loc[13,'bedRoom']=np.nan  used to insert the NAN values in between the df
print(data[num_col])
print(data[num_col].isnull().sum())

     price  price_per_sqft  bedRoom  bathroom  floorNum
0     5.25         20115.0        5         4       3.0
1     5.70        105751.0        5         4       2.0
2     2.10         38251.0       10        10       5.0
3     5.00         43066.0       21        21       5.0
4     3.00         53763.0       12        12       5.0
..     ...             ...      ...       ...       ...
959   5.50         30556.0        4         4       2.0
960   4.25         31481.0        3         2       2.0
961   4.50         33333.0        3         3       2.0
962   3.25         33129.0        3         3       2.0
963   3.60         14815.0        3         3       2.0

[964 rows x 5 columns]
price             19
price_per_sqft    19
bedRoom            0
bathroom           0
floorNum          19
dtype: int64

In [290]:
data[num_col] = data[num_col].fillna(data[num_col].mean())

C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\1777647825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[num_col] = data[num_col].fillna(data[num_col].mean())

In [291]:
data[cat_col] = data[cat_col].fillna(data[cat_col].mode().iloc[0])

C:\Users\Admin\AppData\Local\Temp\ipykernel_12472\2424575533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[cat_col] = data[cat_col].fillna(data[cat_col].mode().iloc[0])

In [292]:
print(data[num_col].isnull().sum())

price             0
price_per_sqft    0
bedRoom           0
bathroom          0
floorNum          0
dtype: int64

In [293]:
print(data[cat_col].isnull().sum())

property_type     0
balcony           0
additionalRoom    0
rating            0
facing            0
agePossession     0
dtype: int64

In [294]:
print(data.isnull().sum())

property_type     0
price             0
price_per_sqft    0
bedRoom           0
bathroom          0
balcony           0
additionalRoom    0
rating            0
floorNum          0
facing            0
agePossession     0
dtype: int64

In [295]:
#convert all the catagorical data into numeric data 
data = pd.get_dummies(data , columns=cat_col,drop_first=True)

In [336]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [337]:
print(data.columns)
print(data.dtypes)

Index(['price', 'price_per_sqft', 'bedRoom', 'bathroom', 'floorNum',
       'balcony_1', 'balcony_2', 'balcony_3', 'balcony_3+',
       'additionalRoom_others',
       ...
       'agePossession_Dec 2023', 'agePossession_Dec 2024',
       'agePossession_Jan 2024', 'agePossession_Jun 2024',
       'agePossession_Oct 2023', 'agePossession_Oct 2024',
       'agePossession_Under Construction', 'agePossession_Within 3 months',
       'agePossession_Within 6 months', 'agePossession_undefined'],
      dtype='object', length=156)
price                               float64
price_per_sqft                      float64
bedRoom                               int64
bathroom                              int64
floorNum                            float64
                                     ...
agePossession_Oct 2024                 bool
agePossession_Under Construction       bool
agePossession_Within 3 months          bool
agePossession_Within 6 months          bool
agePossession_undefined                bool
Length: 156, dtype: object

In [338]:
X = data.drop(columns=['price']) # input features 
Y = data['price'] #output features

In [339]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y , test_size=0.2 , random_state=2)

In [340]:
model = LinearRegression()
model.fit(X_train , Y_train)

LinearRegression()

In [341]:
print(Y_train)

18      7.35
652    17.00
452     1.60
251     8.00
715     7.25
       ...
534     9.90
584    10.55
493     2.43
527     0.89
168     1.16
Name: price, Length: 771, dtype: float64

In [342]:
print(Y_test) #actual price

338     0.650000
183     0.950000
712    12.000000
197     0.450000
141     0.500000
         ...
729     8.490000
456     0.550000
742     4.911069
293     3.500000
62      4.500000
Name: price, Length: 193, dtype: float64

In [343]:
print(X_test)

     price_per_sqft  bedRoom  bathroom  floorNum  balcony_1  balcony_2  \
338     6500.000000        6         2       1.0      False      False
183    10555.000000        3         2       3.0      False       True
712    42194.000000        4         5       4.0      False      False
197    90000.000000        5         3       1.0      False      False
141     7407.000000        5         4       3.0      False      False
..              ...      ...       ...       ...        ...        ...
729    31444.000000        3         3       4.0      False       True
456     4583.000000        2         2       2.0      False      False
742    28251.213757        5         5       2.0      False      False
293   133079.000000        8         8       3.0      False      False
62     20000.000000        5         5       1.0       True      False

     balcony_3  balcony_3+  additionalRoom_others  additionalRoom_pooja room  \
338       True       False                  False                      False
183      False       False                  False                      False
712      False        True                  False                      False
197      False       False                  False                      False
141       True       False                  False                       True
..         ...         ...                    ...                        ...
729      False       False                  False                      False
456      False       False                  False                      False
742      False        True                  False                      False
293      False        True                  False                      False
62       False       False                  False                      False

     ...  agePossession_Dec 2023  agePossession_Dec 2024  \
338  ...                   False                   False
183  ...                   False                   False
712  ...                   False                   False
197  ...                   False                   False
141  ...                   False                   False
..   ...                     ...                     ...
729  ...                   False                   False
456  ...                   False                   False
742  ...                   False                   False
293  ...                   False                   False
62   ...                   False                   False

     agePossession_Jan 2024  agePossession_Jun 2024  agePossession_Oct 2023  \
338                   False                   False                   False
183                   False                   False                   False
712                   False                   False                   False
197                   False                   False                   False
141                   False                   False                   False
..                      ...                     ...                     ...
729                   False                   False                   False
456                   False                   False                   False
742                   False                   False                   False
293                   False                   False                   False
62                    False                   False                   False

     agePossession_Oct 2024  agePossession_Under Construction  \
338                   False                             False
183                   False                             False
712                   False                             False
197                   False                             False
141                   False                             False
..                      ...                               ...
729                   False                             False
456                   False                             False
742                   False                             False
293                   False                             False
62                    False                             False

     agePossession_Within 3 months  agePossession_Within 6 months  \
338                          False                          False
183                          False                          False
712                          False                          False
197                          False                          False
141                          False                          False
..                             ...                            ...
729                          False                          False
456                          False                          False
742                          False                          False
293                          False                          False
62                           False                          False

     agePossession_undefined
338                     True
183                    False
712                    False
197                     True
141                    False
..                       ...
729                    False
456                     True
742                    False
293                    False
62                     False

[193 rows x 155 columns]

In [347]:
Y_pred = model.predict(X.iloc[338:339])
print(Y_pred)

[0.70964705]

In [326]:
from sklearn.metrics import r2_score

In [327]:
result = r2_score(Y_test,Y_pred)
print(result)

0.3644979158038566